#
#  ██╗░░░██╗██╗░░░░░████████╗██████╗░░█████╗░░██████╗████████╗░█████╗░███████╗███████╗
#   ██║░░░██║██║░░░░░╚══██╔══╝██╔══██╗██╔══██╗██╔════╝╚══██╔══╝██╔══██╗██╔════╝██╔════╝
#   ██║░░░██║██║░░░░░░░░██║░░░██████╔╝███████║╚█████╗░░░░██║░░░███████║█████╗░░█████╗░░
#   ██║░░░██║██║░░░░░░░░██║░░░██╔══██╗██╔══██║░╚═══██╗░░░██║░░░██╔══██║██╔══╝░░██╔══╝░░
#   ╚██████╔╝███████╗░░░██║░░░██║░░██║██║░░██║██████╔╝░░░██║░░░██║░░██║██║░░░░░██║░░░░░
#   ░╚═════╝░╚══════╝░░░╚═╝░░░╚═╝░░╚═╝╚═╝░░╚═╝╚═════╝░░░░╚═╝░░░╚═╝░░╚═╝╚═╝░░░░░╚═╝░░░░░
#
#Plugin created by LostString
#UltraStaff: Version 1.6-SNAPSHOT
config:
  staffchat_format: "&7[&bStaffChat&7] &a%player_name% &7>> &9%message%"
  staffchat_format_discord: "&7[&bStaffChat&7] &0(&3Discord&0) &a%player_name% &7>> &9%message%"
  execute_command_on_disconect: true
  frozen_disconnect_command: "ban %player% Refuse SS"
  alerts:
    disabled_worlds:
      - "mines"
      - "spawn"
  vanish_restrictions: true
  report_system: true
  staffmode:
    restrictions: true
    items:
      invsee:
        enabled: true
        item: "CHEST"
        data: 0
        name: "&bInvsee"
        slot: 0
        lore:
          - "&bSee player inventory"
      freeze:
        enabled: true
        item: "ICE"
        data: 0
        name: "&bFreeze"
        slot: 1
        lore:
          - "&aFreeze a player"
      world_edit:
        enabled: true
        item: "WOOD_AXE"
        data: 0
        name: "&cWorld edit"
        slot: 2
        lore:
          - "&cWorldEdit axe"
      navigator:
        enabled: true
        item: "COMPASS"
        data: 0
        name: "&bNavigator"
        slot: 3
        lore:
          - ""
      randomtp:
        enabled: true
        item: "ENDER_PEARL"
        data: 0
        name: "&9Random TP"
        slot: 5
        lore:
          - "&cTeleport to a random player"
      fly:
        enabled: true
        item: "FEATHER"
        data: 0
        name: "&3Fly"
        slot: 6
        lore:
          - "&aEnable &bor &cDisable &bfly"
      vanish:
        enabled: true
        item: "INK_SACK"
        data: 10
        name: "&5Vanish"
        slot: 7
        lore:
          - "&aEnable &bor &cDisable &bvanish"
  immune_to_freeze:
    - "LostString"
  discord:
    enabled: false
    token: "YourBotToken"
    status: "ONLINE"
    activity:
      name: "Minecraft"
      ## types: DEFAULT, WATCHING, COMPETING, LISTENING
      type: "DEFAULT"
    staffchat: "CHANNEL ID"
    staffchat_discord_format: "**STAFF** %player% >> %message%"
    logs_channel: "CHANNEL ID"
    reports_channel: "CHANNEL ID"
    send_logs:
      commands: true
      join: true
      leave: true
      report: true
    Report:
      title: "New Report"
      description: ""
      color: "#FFFFF"
      footer:
        text: "Powered by: StaffUtils"
        icon_url: "https://images-ext-2.discordapp.net/external/iSa8LgfhP5WXg3eMNgPpT3Dfy0zGuGsuC0wBYeh0cQM/https/cdn.discordapp.com/avatars/1087081180312109107/a499774dcbd4c15d7a735da8da505cce.png"
      fields:
        - name: "Player:"
          value: "%player%"
          inline: false
        - name: "Reported:"
          value: "%reported%"
          inline: false
        - name: "Reason:"
          value: "%reason%"
          inline: false
        - name: "Date:"
          value: "%date%"
          inline: false
    Joinlog:
      title: "Join log"
      description: ""
      color: "#FFFFF"
      footer:
        text: "Powered by: StaffUtils"
        icon_url: "https://images-ext-2.discordapp.net/external/iSa8LgfhP5WXg3eMNgPpT3Dfy0zGuGsuC0wBYeh0cQM/https/cdn.discordapp.com/avatars/1087081180312109107/a499774dcbd4c15d7a735da8da505cce.png"
      fields:
        - name: "Log:"
          value: "%player% has joined to the server"
          inline: false
    Leavelog:
      title: "Leave log"
      description: ""
      color: "#FFFFF"
      footer:
        text: "Powered by: StaffUtils"
        icon_url: "https://images-ext-2.discordapp.net/external/iSa8LgfhP5WXg3eMNgPpT3Dfy0zGuGsuC0wBYeh0cQM/https/cdn.discordapp.com/avatars/1087081180312109107/a499774dcbd4c15d7a735da8da505cce.png"
      fields:
        - name: "Log:"
          value: "%player% has leaved to the server"
          inline: false
    Commandlog:
      title: "Command log"
      description: ""
      color: "#FFFFF"
      footer:
        text: "Powered by: StaffUtils"
        icon_url: "https://images-ext-2.discordapp.net/external/iSa8LgfhP5WXg3eMNgPpT3Dfy0zGuGsuC0wBYeh0cQM/https/cdn.discordapp.com/avatars/1087081180312109107/a499774dcbd4c15d7a735da8da505cce.png"
      fields:
        - name: "Log:"
          value: "%player% has used a command"
          inline: false
        - name: "Command:"
          value: "%command%"
          inline: false
